<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <NoWarn>$(NoWarn);NU1510;CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.13" />
    <PackageReference Include="QuestPDF" Version="2025.1.0" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\Xinglin.WebReportEditor.Contracts.csproj" />
    <ProjectReference Include="..\Adapter.Excel\Adapter.Excel.csproj" />
    <ProjectReference Include="..\ReportDataMaker.Core\ReportDataMaker.Core.csproj" />
    <ProjectReference Include="..\Adapter.Database.Common\Adapter.Database.Common.csproj" />
    <ProjectReference Include="..\Adapter.Database.SqlServer\Adapter.Database.SqlServer.csproj" />
    <ProjectReference Include="..\Adapter.Database.MySql\Adapter.Database.MySql.csproj" />
    <ProjectReference Include="..\Adapter.Database.PostgreSql\Adapter.Database.PostgreSql.csproj" />
    <ProjectReference Include="..\Adapter.Database.Sqlite\Adapter.Database.Sqlite.csproj" />
    <ProjectReference Include="..\Adapter.Excel\Adapter.Excel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Templates\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
