<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ReportDataMaker</RootNamespace>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QuestPDF" Version="2025.1.0" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\Xinglin.WebReportEditor.Contracts.csproj" />
    <ProjectReference Include="..\..\Rendering\Xinglin.ReportEditor.Rendering.csproj" />
    <ProjectReference Include="..\Adapter.Database.Common\Adapter.Database.Common.csproj" />
    <ProjectReference Include="..\Adapter.Database.SqlServer\Adapter.Database.SqlServer.csproj" />
    <ProjectReference Include="..\Adapter.Database.MySql\Adapter.Database.MySql.csproj" />
    <ProjectReference Include="..\Adapter.Database.PostgreSql\Adapter.Database.PostgreSql.csproj" />
    <ProjectReference Include="..\Adapter.Database.Sqlite\Adapter.Database.Sqlite.csproj" />
  </ItemGroup>

</Project>
